apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-gifvsbmd
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-gifvsbmd:825fa5de47bdf7548500a0341246996032129599@sha256:41adfa8fb1ec3c1a40e7943211c23c24cfa8f451005adfe5f04ac6997745e83b
          name: container-image
